<!--
  Ooba Settings용 ViewerButton 목록
  ModelOobaSettingButtons.svelte에 추가할 코드
-->

<!-- Ooba Settings를 Accordion으로 그룹화 -->
<Accordion name="Ooba Settings" styled>

  <!-- Ooba Mode 선택 -->
  <ViewerButton
    key="ooba.mode"
    value={currentContent.ooba?.mode}
    {fileId}
    fileType="risup"
  />

  <!-- Chat Format Settings (instructionMode일 때만) -->
  {#if instructionMode}
    <!-- name1 = user | name2 = bot -->
    <ViewerButton
      key="ooba.name1_instruct"
      value={currentContent.ooba?.name1_instruct}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.name2_instruct"
      value={currentContent.ooba?.name2_instruct}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.context_instruct"
      value={currentContent.ooba?.context_instruct}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.system_message"
      value={currentContent.ooba?.system_message}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.name1"
      value={currentContent.ooba?.name1}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.name2"
      value={currentContent.ooba?.name2}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.context"
      value={currentContent.ooba?.context}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.greeting"
      value={currentContent.ooba?.greeting}
      {fileId}
      fileType="risup"
    />
    <ViewerButton
      key="ooba.chat_instruct_command"
      value={currentContent.ooba?.chat_instruct_command}
      {fileId}
      fileType="risup"
    />
  {/if}

  <!-- Core Ooba Parameters -->
  <ViewerButton
    key="ooba.tokenizer"
    value={currentContent.ooba?.tokenizer}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.min_p"
    value={currentContent.ooba?.min_p}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.top_k"
    value={currentContent.ooba?.top_k}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.repetition_penalty"
    value={currentContent.ooba?.repetition_penalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.repetition_penalty_range"
    value={currentContent.ooba?.repetition_penalty_range}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.typical_p"
    value={currentContent.ooba?.typical_p}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.tfs"
    value={currentContent.ooba?.tfs}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.top_a"
    value={currentContent.ooba?.top_a}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.epsilon_cutoff"
    value={currentContent.ooba?.epsilon_cutoff}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.eta_cutoff"
    value={currentContent.ooba?.eta_cutoff}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.guidance_scale"
    value={currentContent.ooba?.guidance_scale}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.penalty_alpha"
    value={currentContent.ooba?.penalty_alpha}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.mirostat_mode"
    value={currentContent.ooba?.mirostat_mode}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.mirostat_tau"
    value={currentContent.ooba?.mirostat_tau}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.mirostat_eta"
    value={currentContent.ooba?.mirostat_eta}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.encoder_repetition_penalty"
    value={currentContent.ooba?.encoder_repetition_penalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.no_repeat_ngram_size"
    value={currentContent.ooba?.no_repeat_ngram_size}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.min_length"
    value={currentContent.ooba?.min_length}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.num_beams"
    value={currentContent.ooba?.num_beams}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.length_penalty"
    value={currentContent.ooba?.length_penalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.truncation_length"
    value={currentContent.ooba?.truncation_length}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.max_tokens_second"
    value={currentContent.ooba?.max_tokens_second}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.negative_prompt"
    value={currentContent.ooba?.negative_prompt}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.custom_token_bans"
    value={currentContent.ooba?.custom_token_bans}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.grammar_string"
    value={currentContent.ooba?.grammar_string}
    {fileId}
    fileType="risup"
  />

  <!-- Boolean Parameters -->
  <ViewerButton
    key="ooba.temperature_last"
    value={currentContent.ooba?.temperature_last}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.do_sample"
    value={currentContent.ooba?.do_sample}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.early_stopping"
    value={currentContent.ooba?.early_stopping}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.auto_max_new_tokens"
    value={currentContent.ooba?.auto_max_new_tokens}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.ban_eos_token"
    value={currentContent.ooba?.ban_eos_token}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.add_bos_token"
    value={currentContent.ooba?.add_bos_token}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.skip_special_tokens"
    value={currentContent.ooba?.skip_special_tokens}
    {fileId}
    fileType="risup"
  />

  <!-- Local Stop Strings (instructionMode일 때만) -->
  {#if instructionMode}
    <ViewerButton
      key="localStopStrings"
      value={currentContent.localStopStrings}
      {fileId}
      fileType="risup"
    />
  {/if}

</Accordion>