<!--
  RisupViewer에 추가할 조건부 ViewerButton 코드
  기존 ViewerButton들 아래에 삽입하세요
-->

<!-- ooba/textgen 모델 파라미터들 -->
{#if currentContent.aiModel === "textgen_webui" || currentContent.aiModel === "mancer" || currentContent.aiModel.startsWith("local_") || currentContent.aiModel.startsWith("hf:::")}
  <ViewerButton
    key="ooba.repetition_penalty"
    value={currentContent.ooba?.repetition_penalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.length_penalty"
    value={currentContent.ooba?.length_penalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.top_k"
    value={currentContent.ooba?.top_k}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.top_p"
    value={currentContent.ooba?.top_p}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.typical_p"
    value={currentContent.ooba?.typical_p}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.top_a"
    value={currentContent.ooba?.top_a}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.no_repeat_ngram_size"
    value={currentContent.ooba?.no_repeat_ngram_size}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.do_sample"
    value={currentContent.ooba?.do_sample}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.add_bos_token"
    value={currentContent.ooba?.add_bos_token}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.ban_eos_token"
    value={currentContent.ooba?.ban_eos_token}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.skip_special_tokens"
    value={currentContent.ooba?.skip_special_tokens}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="localStopStrings"
    value={currentContent.localStopStrings}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ooba.formating.useName"
    value={currentContent.ooba?.formating?.useName}
    {fileId}
    fileType="risup"
  />
{/if}

<!-- NovelAI 모델 파라미터들 -->
{#if dynamicModelInfo.format === LLMFormat.NovelAI}
  <ViewerButton
    key="NAIsettings.starter"
    value={currentContent.NAIsettings?.starter}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.seperator"
    value={currentContent.NAIsettings?.seperator}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.topP"
    value={currentContent.NAIsettings?.topP}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.topK"
    value={currentContent.NAIsettings?.topK}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.topA"
    value={currentContent.NAIsettings?.topA}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.tailFreeSampling"
    value={currentContent.NAIsettings?.tailFreeSampling}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.typicalp"
    value={currentContent.NAIsettings?.typicalp}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.repetitionPenalty"
    value={currentContent.NAIsettings?.repetitionPenalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.repetitionPenaltyRange"
    value={currentContent.NAIsettings?.repetitionPenaltyRange}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.repetitionPenaltySlope"
    value={currentContent.NAIsettings?.repetitionPenaltySlope}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.frequencyPenalty"
    value={currentContent.NAIsettings?.frequencyPenalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.presencePenalty"
    value={currentContent.NAIsettings?.presencePenalty}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.mirostat_lr"
    value={currentContent.NAIsettings?.mirostat_lr}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.mirostat_tau"
    value={currentContent.NAIsettings?.mirostat_tau}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="NAIsettings.cfg_scale"
    value={currentContent.NAIsettings?.cfg_scale}
    {fileId}
    fileType="risup"
  />
{/if}

<!-- NovelList 모델 파라미터들 -->
{#if dynamicModelInfo.format === LLMFormat.NovelList}
  <ViewerButton
    key="ainconfig.top_p"
    value={currentContent.ainconfig?.top_p}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ainconfig.rep_pen"
    value={currentContent.ainconfig?.rep_pen}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ainconfig.rep_pen_range"
    value={currentContent.ainconfig?.rep_pen_range}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ainconfig.rep_pen_slope"
    value={currentContent.ainconfig?.rep_pen_slope}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ainconfig.top_k"
    value={currentContent.ainconfig?.top_k}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ainconfig.top_a"
    value={currentContent.ainconfig?.top_a}
    {fileId}
    fileType="risup"
  />
  <ViewerButton
    key="ainconfig.typical_p"
    value={currentContent.ainconfig?.typical_p}
    {fileId}
    fileType="risup"
  />
{/if}